version: '2'

services:
  app:
    build: .
    image: pet-tracker
    command: amber watch
    environment:
      DATABASE_URL: mysql://root:root@db:3306/pet_tracker_development
    ports:
      - 3000:3000
    links:
      - db
    volumes:
    - .:/app
    - nodes:/app/node_modules
    - shards:/app/lib

  migrate:
    build: .
    image: pet-tracker
    command: bash -c 'while ! nc -q 1 db 5432 </dev/null; do sleep 1; done && amber db migrate seed'
    environment:
      DATABASE_URL: mysql://root:root@db:3306/pet_tracker_development
    volumes:
      - .:/app
    links:
      - db

  db:
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: pet_tracker_development
    volumes:
      - db:/var/lib/mysql/data

volumes:
  db:
  nodes:
  shards:
